// Builds proxy/src/sim/ from the game's own simulation worker, so the Worker checks runs
// with exactly the physics the game uses.
//   node tools/build-sim.js [captured-init.json]
// The capture is only needed to rebuild init.bin (see PROXY.md, "Anti-cheat").
const fs = require("fs");
const path = require("path");

const GAME = path.resolve(__dirname, "../..");
const OUT = path.resolve(__dirname, "../src/sim");
fs.mkdirSync(OUT, { recursive: true });

function replaceOnce(text, find, replacement, label) {
    const count = typeof find === "string" ? text.split(find).length - 1 : (text.match(new RegExp(find.source, "g")) || []).length;
    if (count !== 1) throw new Error(`${label}: expected 1 match, found ${count}`);
    return text.replace(find, replacement);
}

let bundle = fs.readFileSync(path.join(GAME, "simulation_worker.bundle.js"), "utf8");
const glue = fs.readFileSync(path.join(GAME, "lib/polytrack_physics.js"), "utf8");

// Workers can't compile wasm from bytes, so the maths module becomes an imported file.
const mathMatch = bundle.match(/const t = Uint8Array\.from\(atob\("([A-Za-z0-9+/=]+)"\), \(t => t\.charCodeAt\(0\)\)\)\s*,\s*e = await WebAssembly\.compile\(t\)\s*,\s*i = \(await WebAssembly\.instantiate\(e\)\)\.exports;/)
    || bundle.match(/const t = Uint8Array\.from\(atob\("([A-Za-z0-9+/=]+)"\)[^;]*?,\s*e = await WebAssembly\.compile\(t\)\s*,\s*i = \(await WebAssembly\.instantiate\(e\)\)\.exports;/);
if (!mathMatch) throw new Error("maths wasm not found");
fs.writeFileSync(path.join(OUT, "math.wasm"), Buffer.from(mathMatch[1], "base64"));
bundle = replaceOnce(bundle, mathMatch[0], "const i = (await WebAssembly.instantiate(__mathModule)).exports;", "maths wasm");

bundle = replaceOnce(bundle, 'importScripts("lib/polytrack_physics.js");', "", "importScripts");
bundle = replaceOnce(bundle, "PolyTrackPhysics().then(", "PolyTrackPhysics(__physicsOptions).then(", "physics options");
// The non-realtime loop only drives cars created with CreateCar; checking runs never needs it.
bundle = replaceOnce(bundle, /else\s+setInterval\(c\)/, "else;", "idle loop");
bundle = replaceOnce(bundle, /jo\.length = 0,\s+onmessage = i;/, "jo.length = 0,\n            onmessage = i,\n            queueMicrotask(__ready);", "ready hook");

fs.copyFileSync(path.join(GAME, "polytrack_physics.wasm"), path.join(OUT, "physics.wasm"));

const source = `// Generated by proxy/tools/build-sim.js from simulation_worker.bundle.js and
// lib/polytrack_physics.js. Don't edit by hand; rebuild instead.
export function startSimulation(physicsModule, mathModule, onMessage) {
    // The game swaps Math for deterministic versions; this keeps the swap inside here.
    let Math = globalThis.Math;
    const self = { location: { href: "https://localhost/simulation_worker.bundle.js" } };
    // Keeps the bundled sha256 library on its browser path.
    const process = undefined;
    let onmessage = null;
    const postMessage = (message) => onMessage(message);
    const __mathModule = mathModule;
    const __physicsOptions = {
        instantiateWasm(imports, done) {
            WebAssembly.instantiate(physicsModule, imports).then((instance) => done(instance, physicsModule));
            return {};
        },
    };
    let __ready;
    const ready = new Promise((resolve) => (__ready = resolve));
${glue}
${bundle}
    return { ready, send: (data) => onmessage({ data }) };
}
`;
fs.writeFileSync(path.join(OUT, "simulation.js"), source);

const capture = process.argv[2];
if (capture) {
    const init = JSON.parse(fs.readFileSync(capture, "utf8"));
    const parts = init.trackParts.map((p) => ({ id: p.id, detector: p.detector, startOffset: p.startOffset, count: p.vertices.length }));
    let header = JSON.stringify({ parts, carMassOffset: init.carMassOffset, carCount: init.carCollisionShapeVertices.length });
    // Padded so the floats start 4-byte aligned and can be read without a copy.
    header = Buffer.from(header + " ".repeat((4 - ((4 + Buffer.byteLength(header)) % 4)) % 4));
    const floats = new Float32Array(parts.reduce((n, p) => n + p.count, 0) + init.carCollisionShapeVertices.length);
    let o = 0;
    for (const p of init.trackParts) for (const v of p.vertices) floats[o++] = v;
    for (const v of init.carCollisionShapeVertices) floats[o++] = v;
    const size = Buffer.alloc(4);
    size.writeUInt32LE(header.length);
    fs.writeFileSync(path.join(OUT, "init.bin"), Buffer.concat([size, header, Buffer.from(floats.buffer)]));
}
console.log("built", fs.readdirSync(OUT).map((f) => f + " " + fs.statSync(path.join(OUT, f)).size).join(", "));
